version: '3'
services:

  fedora:
    build: 
      context: .
      dockerfile: Dockerfile.fedora
    volumes:
      - .:/opt/src

  debian:
    build: 
      context: .
      dockerfile: Dockerfile.debian
    volumes:
      - .:/opt/src
