FROM fedora:32 as builder

RUN dnf update -y
RUN dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-32.noarch.rpm
RUN dnf install -y obs-studio-libs obs-studio-devel qt5-qtbase-devel cmake make automake gcc gcc-c++ --enablerepo=rpmfusion-free-updates

VOLUME /opt/src

CMD mkdir -p /opt/src/build-fedora && \
    cd /opt/src && \
    rm -rf /opt/src/build-fedora/* && \
    cd /opt/src/build-fedora && \
    cmake .. -DCMAKE_INSTALL_PREFIX=/usr && \
    make -j4
